### PR TITLE
Add connectionType local

### PR DESCRIPTION
**Pull request by guerda**
Add connectionType which is required in the io-package.json according to adapterchecker.

### CODE REVIEW

**Comment by guerda** [comment]
According to adapter-check.in this fixes the dataSource error. I ran it against my branch.

**Comment by mobilutz** [comment]
@guerda I will add you to this repo, so that you don't need to fork is to your github account to add branches.

I then could also fix the merge conflicts 😉

**Comment by guerda** [comment]
Sure, sounds good!

**Comment by guerda** [comment]
I resolved the conflict accordingly. Should be mergable.

**Review by mobilutz — APPROVED** [review]

**Pull request merged**
