### PR TITLE
Fix naming

### PR DESCRIPTION
**Pull request by guerda**
Fixed a name, according to adapterchecker

### CODE REVIEW

**Comment by guerda** [comment]
Fixes parts of #15 and #20.

**Comment by guerda** [comment]
According to adapter-check.in this fixes the names error. I ran it against my branch.

**Review by mobilutz — COMMENTED** [review]
I don't think that this is really what we should have here.
Seeing other adapters, this element always has the name of the adapter in it.
Example: https://github.com/ioBroker/ioBroker.web/blob/master/io-package.json#L3

@guerda Maybe the error is there, because this repo is under my personal github name.

**Comment by guerda** [comment]
Yeah, I was confused about that, too. Indeed, the checker says that the name must be empty, but maybe that's a follow up error.

The error messages are not too helpful in fixing those. I will investigate.

**Pull request closed without merging**
